import re
from datetime import datetime, timezone

CITY_TZ = {
    "Hong Kong": 8,
    "Seoul": 9,
    "Busan": 9,
    "Incheon": 9,
    "Pyongyang": 9,
    "Tokyo": 9,
    "Osaka": 9,
    "Kyoto": 9,
    "Yokohama": 9,
    "Nagoya": 9,
    "Sapporo": 9,
    "Fukuoka": 9,
    "Beijing": 8,
    "Shanghai": 8,
    "Guangzhou": 8,
    "Shenzhen": 8,
    "Chengdu": 8,
    "Chongqing": 8,
    "Tianjin": 8,
    "Nanjing": 8,
    "Hangzhou": 8,
    "Wuhan": 8,
    "Xi'an": 8,
    "Manila": 8,
    "Quezon City": 8,
    "Davao": 8,
    "Kuala Lumpur": 8,
    "Singapore": 8,
    "Jakarta": 7,
    "Surabaya": 7,
    "Bandung": 7,
    "Bangkok": 7,
    "Chiang Mai": 7,
    "Phuket": 7,
    "Hanoi": 7,
    "Ho Chi Minh City": 7,
    "Taipei": 8,
    "Dubai": 4,
    "Abu Dhabi": 4,
    "Doha": 3,
    "Riyadh": 3,
    "Jeddah": 3,
    "Mecca": 3,
    "Medina": 3,
    "Dammam": 3,
    "Kuwait City": 3,
    "Muscat": 4,
    "Tehran": 3.5,
    "Mashhad": 3.5,
    "Isfahan": 3.5,
    "Tel Aviv": 3,
    "Jerusalem": 3,
    "Istanbul": 3,
    "Ankara": 3,
    "Izmir": 3,
    "Karachi": 5,
    "Lahore": 5,
    "Faisalabad": 5,
    "Rawalpindi": 5,
    "Islamabad": 5,
    "Multan": 5,
    "Hyderabad": 5,
    "Peshawar": 5,
    "Quetta": 5,
    "Mumbai": 5.5,
    "Delhi": 5.5,
    "New Delhi": 5.5,
    "Bangalore": 5.5,
    "Chennai": 5.5,
    "Kolkata": 5.5,
    "Hyderabad": 5.5,
    "Ahmedabad": 5.5,
    "Pune": 5.5,
    "Jaipur": 5.5,
    "Lucknow": 5.5,
    "Kanpur": 5.5,
    "Nagpur": 5.5,
    "Indore": 5.5,
    "Bhopal": 5.5,
    "Patna": 5.5,
    "Surat": 5.5,
    "Visakhapatnam": 5.5,
    "Vadodara": 5.5,
    "Guwahati": 5.5,
    "Chandigarh": 5.5,
    "Dhaka": 6,
    "Chittagong": 6,
    "Colombo": 5.5,
    "Kathmandu": 5.75,
    "Kabul": 4.5,
    "Tashkent": 5,
    "Almaty": 5,
    "Astana": 5,
    "Ulaanbaatar": 8,
    "Phnom Penh": 7,
    "Vientiane": 7,
    "Yangon": 6.5,
    "Naypyidaw": 6.5,
    "London": 1,
    "Manchester": 1,
    "Birmingham": 1,
    "Liverpool": 1,
    "Glasgow": 1,
    "Edinburgh": 1,
    "Leeds": 1,
    "Bristol": 1,
    "Sheffield": 1,
    "Paris": 2,
    "Marseille": 2,
    "Lyon": 2,
    "Toulouse": 2,
    "Nice": 2,
    "Berlin": 2,
    "Hamburg": 2,
    "Munich": 2,
    "Cologne": 2,
    "Frankfurt": 2,
    "Stuttgart": 2,
    "Dusseldorf": 2,
    "Dresden": 2,
    "Leipzig": 2,
    "Hannover": 2,
    "Nuremberg": 2,
    "Madrid": 2,
    "Barcelona": 2,
    "Valencia": 2,
    "Seville": 2,
    "Zaragoza": 2,
    "Malaga": 2,
    "Murcia": 2,
    "Palma": 2,
    "Bilbao": 2,
    "Alicante": 2,
    "Cordoba": 2,
    "Rome": 2,
    "Milan": 2,
    "Naples": 2,
    "Turin": 2,
    "Palermo": 2,
    "Genoa": 2,
    "Florence": 2,
    "Bologna": 2,
    "Venice": 2,
    "Vienna": 2,
    "Prague": 2,
    "Warsaw": 2,
    "Krakow": 2,
    "Wroclaw": 2,
    "Poznan": 2,
    "Gdansk": 2,
    "Budapest": 2,
    "Bucharest": 3,
    "Sofia": 3,
    "Athens": 3,
    "Thessaloniki": 3,
    "Moscow": 3,
    "Saint Petersburg": 3,
    "Novosibirsk": 7,
    "Yekaterinburg": 5,
    "Nizhny Novgorod": 3,
    "Kazan": 3,
    "Chelyabinsk": 5,
    "Omsk": 6,
    "Samara": 4,
    "Rostov-on-Don": 3,
    "Ufa": 5,
    "Krasnoyarsk": 7,
    "Voronezh": 3,
    "Perm": 5,
    "Volgograd": 3,
    "Kiev": 3,
    "Kharkiv": 3,
    "Odessa": 3,
    "Dnipro": 3,
    "Minsk": 3,
    "Stockholm": 2,
    "Oslo": 2,
    "Copenhagen": 2,
    "Helsinki": 3,
    "Riga": 3,
    "Vilnius": 3,
    "Tallinn": 3,
    "Belgrade": 2,
    "Zagreb": 2,
    "Ljubljana": 2,
    "Sarajevo": 2,
    "Skopje": 2,
    "Tirana": 2,
    "Podgorica": 2,
    "Pristina": 2,
    "Zurich": 2,
    "Geneva": 2,
    "Bern": 2,
    "Basel": 2,
    "Lausanne": 2,
    "Amsterdam": 2,
    "Rotterdam": 2,
    "The Hague": 2,
    "Utrecht": 2,
    "Brussels": 2,
    "Antwerp": 2,
    "Ghent": 2,
    "Charleroi": 2,
    "Dublin": 1,
    "Cork": 1,
    "Lisbon": 1,
    "Porto": 1,
    "Reykjavik": 0,
    "Brasilia": -3,
    "Rio de Janeiro": -3,
    "Sao Paulo": -3,
    "Salvador": -3,
    "Fortaleza": -3,
    "Belo Horizonte": -3,
    "Manaus": -4,
    "Curitiba": -3,
    "Recife": -3,
    "Porto Alegre": -3,
    "Belem": -3,
    "Buenos Aires": -3,
    "Cordoba": -3,
    "Rosario": -3,
    "Mendoza": -3,
    "La Paz": -4,
    "Santa Cruz": -4,
    "Santiago": -4,
    "Valparaiso": -4,
    "Concepcion": -4,
    "Lima": -5,
    "Arequipa": -5,
    "Quito": -5,
    "Guayaquil": -5,
    "Bogota": -5,
    "Medellin": -5,
    "Cali": -5,
    "Barranquilla": -5,
    "Caracas": -4,
    "Maracaibo": -4,
    "Mexico City": -6,
    "Guadalajara": -6,
    "Monterrey": -6,
    "Puebla": -6,
    "Tijuana": -7,
    "Cancun": -5,
    "New York": -4,
    "Los Angeles": -7,
    "Chicago": -5,
    "Houston": -5,
    "Phoenix": -7,
    "Philadelphia": -4,
    "San Antonio": -5,
    "San Diego": -7,
    "Dallas": -5,
    "San Jose": -7,
    "Austin": -5,
    "Jacksonville": -4,
    "Fort Worth": -5,
    "Columbus": -4,
    "Charlotte": -4,
    "Indianapolis": -4,
    "San Francisco": -7,
    "Seattle": -7,
    "Denver": -6,
    "Nashville": -5,
    "Oklahoma City": -5,
    "El Paso": -6,
    "Washington": -4,
    "Boston": -4,
    "Las Vegas": -7,
    "Portland": -7,
    "Memphis": -5,
    "Louisville": -4,
    "Baltimore": -4,
    "Milwaukee": -5,
    "Albuquerque": -6,
    "Tucson": -7,
    "Fresno": -7,
    "Sacramento": -7,
    "Mesa": -7,
    "Kansas City": -5,
    "Atlanta": -4,
    "Omaha": -5,
    "Colorado Springs": -6,
    "Raleigh": -4,
    "Long Beach": -7,
    "Virginia Beach": -4,
    "Miami": -4,
    "Oakland": -7,
    "Minneapolis": -5,
    "Tampa": -4,
    "Tulsa": -5,
    "Arlington": -5,
    "New Orleans": -5,
    "Cleveland": -4,
    "Bakersfield": -7,
    "Honolulu": -10,
    "Anchorage": -8,
    "Calgary": -6,
    "Edmonton": -6,
    "Toronto": -4,
    "Montreal": -4,
    "Vancouver": -7,
    "Ottawa": -4,
    "Winnipeg": -5,
    "Quebec City": -4,
    "Hamilton": -4,
    "Halifax": -3,
    "Cape Town": 2,
    "Johannesburg": 2,
    "Pretoria": 2,
    "Durban": 2,
    "Port Elizabeth": 2,
    "Bloemfontein": 2,
    "Lagos": 1,
    "Abuja": 1,
    "Ibadan": 1,
    "Kano": 1,
    "Port Harcourt": 1,
    "Benin City": 1,
    "Nairobi": 3,
    "Mombasa": 3,
    "Dar es Salaam": 3,
    "Dodoma": 3,
    "Addis Ababa": 3,
    "Dire Dawa": 3,
    "Cairo": 3,
    "Alexandria": 3,
    "Giza": 3,
    "Luxor": 3,
    "Aswan": 3,
    "Khartoum": 2,
    "Omdurman": 2,
    "Casablanca": 1,
    "Rabat": 1,
    "Fes": 1,
    "Marrakech": 1,
    "Tangier": 1,
    "Algiers": 1,
    "Oran": 1,
    "Tunis": 1,
    "Tripoli": 2,
    "Accra": 0,
    "Kumasi": 0,
    "Dakar": 0,
    "Bamako": 0,
    "Ouagadougou": 0,
    "Abidjan": 0,
    "Yaounde": 1,
    "Douala": 1,
    "Luanda": 1,
    "Lubumbashi": 2,
    "Kinshasa": 1,
    "Harare": 2,
    "Lusaka": 2,
    "Maputo": 2,
    "Antananarivo": 3,
    "Mogadishu": 3,
    "Perth": 8,
    "Adelaide": 9.5,
    "Melbourne": 10,
    "Sydney": 10,
    "Brisbane": 10,
    "Gold Coast": 10,
    "Canberra": 10,
    "Newcastle": 10,
    "Wollongong": 10,
    "Hobart": 10,
    "Darwin": 9.5,
    "Auckland": 12,
    "Wellington": 12,
    "Christchurch": 12,
    "Hamilton": 12,
    "Tauranga": 12,
    "Dunedin": 12,
}


def get_city_utc_offset(city_name):
    return CITY_TZ.get(city_name)


def extract_city_from_question(question):
    m = re.search(r'in\s+([A-Za-z\s-]+?)(?:\s+be\s)', question)
    if m:
        return m.group(1).strip()
    return None


def is_after_3pm_local(utc_offset):
    now_utc = datetime.now(timezone.utc)
    offset_hours = int(utc_offset)
    offset_minutes = int(abs(utc_offset - offset_hours) * 60)
    if utc_offset < 0:
        offset_minutes = -offset_minutes
    local_hour = (now_utc.hour + offset_hours) % 24
    local_min = now_utc.minute + offset_minutes
    if local_min >= 60:
        local_hour += 1
        local_min -= 60
    elif local_min < 0:
        local_hour -= 1
        local_min += 60
    local_hour %= 24
    return local_hour >= 15
